image:
  repository: thang05/typ-backend
  tag: "v1.0.1"
  pullPolicy: IfNotPresent

service:
  name: student-backend
  port: 3000

env:
  PORT: "3000"

  DB_HOST: "student-mysql"
  DB_PORT: "3306"
  DB_NAME: "studentdb"
  DB_USER: "appuser"
  DB_PASSWORD: "apppass"

ingress:
  enabled: true
  className: nginx
  host: api.typ-app.local
  path: /
  tls:
    enabled: true
    secretName: typ-tls-secret
  annotations: {}