image:
  repository: thang05/typ-backend
  tag: "v2.0.5"
  pullPolicy: IfNotPresent

service:
  name: student-backend
  port: 3000

env:
  PORT: "3000"

  DB_HOST: "student-mysql"
  DB_PORT: "3306"
  DB_NAME: "studentdb"
  DB_USER: "appuser"
  DB_PASSWORD: "apppass"
